'------------------------------------------------------------------------------
' <auto-generated>
'     Der Code wurde von einer Vorlage generiert.
'
'     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
'     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class AusleiheEntity
    Public Property ausID As Integer
    Public Property ausStart As Nullable(Of Date)
    Public Property ausEnde As Nullable(Of Date)
    Public Property ausgegIDFk As Integer
    Public Property ausbenBenutzernameFk As String

    Public Overridable Property tblBenutzer As BenutzerEntity
    Public Overridable Property tblGegenstand As GegenstandEntity

End Class
