'------------------------------------------------------------------------------
' <auto-generated>
'     Der Code wurde von einer Vorlage generiert.
'
'     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
'     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class BenutzerEntity
    Public Property benBenutzername As String
    Public Property benPasswort As String
    Public Property benVorname As String
    Public Property benName As String
    Public Property benEmail As String
    Public Property benTelefonnummer As String
    Public Property benGeburtsdatum As Date
    Public Property benScore As Integer
    Public Property benIstKoordinator As Boolean
    Public Property benIstEigentümer As Boolean
    Public Property bennachIDFk As Integer

    Public Overridable Property tblnachbarschaft As NachbarschaftEntity
    Public Overridable Property tblGegenstand As ICollection(Of GegenstandEntity) = New HashSet(Of GegenstandEntity)

End Class
