
'------------------------------------------------------------------------------
' <auto-generated>
'    Dieser Code wurde aus einer Vorlage generiert.
'
'    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
'    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.ComponentModel
Imports System.Data.EntityClient
Imports System.Data.Objects
Imports System.Data.Objects.DataClasses
Imports System.Linq
Imports System.Runtime.Serialization
Imports System.Xml.Serialization

<Assembly: EdmSchemaAttribute("070babdb-a1f3-4afa-97de-42d0e63e26fc")>
#Region "EDM-Beziehungsmetadaten"
<Assembly: EdmRelationshipAttribute("Datenbank1Model", "ausbenBenutzernameFk", "tblBenutzer", System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(BenutzerEntity), "tblAusleihe", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(AusleiheEntity), True)>
<Assembly: EdmRelationshipAttribute("Datenbank1Model", "ausgegIDFk", "tblGegenstand", System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(GegenstandEntity), "tblAusleihe", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(AusleiheEntity), True)>
<Assembly: EdmRelationshipAttribute("Datenbank1Model", "bennachIDFk", "tblnachbarschaft", System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(NachbarschaftEntity), "tblBenutzer", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(BenutzerEntity), True)>
<Assembly: EdmRelationshipAttribute("Datenbank1Model", "gegbenIDFk", "tblBenutzer", System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(BenutzerEntity), "tblGegenstand", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(GegenstandEntity), True)>
<Assembly: EdmRelationshipAttribute("Datenbank1Model", "gegkatKategorieFk", "tblKategorie", System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(KategorieEntity), "tblGegenstand", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(GegenstandEntity), True)>
<Assembly: EdmRelationshipAttribute("Datenbank1Model", "gegnachIDFk", "tblnachbarschaft", System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(NachbarschaftEntity), "tblGegenstand", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(GegenstandEntity), True)>

#End Region

#Region "Kontexte"

''' <summary>
''' Keine Dokumentation für Metadaten verfügbar.
''' </summary>
Public Partial Class Datenbank1Entities1
    Inherits ObjectContext

    #Region "Konstruktoren"

    ''' <summary>
    ''' Initialisiert ein neues Datenbank1Entities1-Objekt mithilfe der in Abschnitt 'Datenbank1Entities1' der Anwendungskonfigurationsdatei gefundenen Verbindungszeichenfolge.
    ''' </summary>
    Public Sub New()
        MyBase.New("name=Datenbank1Entities1", "Datenbank1Entities1")
        MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    ''' <summary>
    ''' Initialisiert ein neues Datenbank1Entities1-Objekt.
    ''' </summary>
    Public Sub New(ByVal connectionString As String)
        MyBase.New(connectionString, "Datenbank1Entities1")
        MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    ''' <summary>
    ''' Initialisiert ein neues Datenbank1Entities1-Objekt.
    ''' </summary>
    Public Sub New(ByVal connection As EntityConnection)
        MyBase.New(connection, "Datenbank1Entities1")
        MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    #End Region

    #Region "Partielle Methoden"

    Partial Private Sub OnContextCreated()
    End Sub

    #End Region

    #Region "ObjectSet-Eigenschaften"

    ''' <summary>
    ''' Keine Dokumentation für Metadaten verfügbar.
    ''' </summary>
    Public ReadOnly Property tblAusleihe() As ObjectSet(Of AusleiheEntity)
        Get
            If (_tblAusleihe Is Nothing) Then
                _tblAusleihe = MyBase.CreateObjectSet(Of AusleiheEntity)("tblAusleihe")
            End If
            Return _tblAusleihe
        End Get
    End Property

    Private _tblAusleihe As ObjectSet(Of AusleiheEntity)

    ''' <summary>
    ''' Keine Dokumentation für Metadaten verfügbar.
    ''' </summary>
    Public ReadOnly Property tblBenutzer() As ObjectSet(Of BenutzerEntity)
        Get
            If (_tblBenutzer Is Nothing) Then
                _tblBenutzer = MyBase.CreateObjectSet(Of BenutzerEntity)("tblBenutzer")
            End If
            Return _tblBenutzer
        End Get
    End Property

    Private _tblBenutzer As ObjectSet(Of BenutzerEntity)

    ''' <summary>
    ''' Keine Dokumentation für Metadaten verfügbar.
    ''' </summary>
    Public ReadOnly Property tblGegenstand() As ObjectSet(Of GegenstandEntity)
        Get
            If (_tblGegenstand Is Nothing) Then
                _tblGegenstand = MyBase.CreateObjectSet(Of GegenstandEntity)("tblGegenstand")
            End If
            Return _tblGegenstand
        End Get
    End Property

    Private _tblGegenstand As ObjectSet(Of GegenstandEntity)

    ''' <summary>
    ''' Keine Dokumentation für Metadaten verfügbar.
    ''' </summary>
    Public ReadOnly Property tblKategorie() As ObjectSet(Of KategorieEntity)
        Get
            If (_tblKategorie Is Nothing) Then
                _tblKategorie = MyBase.CreateObjectSet(Of KategorieEntity)("tblKategorie")
            End If
            Return _tblKategorie
        End Get
    End Property

    Private _tblKategorie As ObjectSet(Of KategorieEntity)

    ''' <summary>
    ''' Keine Dokumentation für Metadaten verfügbar.
    ''' </summary>
    Public ReadOnly Property tblnachbarschaft() As ObjectSet(Of NachbarschaftEntity)
        Get
            If (_tblnachbarschaft Is Nothing) Then
                _tblnachbarschaft = MyBase.CreateObjectSet(Of NachbarschaftEntity)("tblnachbarschaft")
            End If
            Return _tblnachbarschaft
        End Get
    End Property

    Private _tblnachbarschaft As ObjectSet(Of NachbarschaftEntity)

    #End Region

    #Region "AddTo-Methoden"

    ''' <summary>
    ''' Veraltete Methode zum Hinzufügen eines neuen Objekts zum EntitySet 'tblAusleihe'. Verwenden Sie stattdessen die Methode '.Add' der zugeordneten Eigenschaft 'ObjectSet(Of T) '.
    ''' </summary>
    Public Sub AddTotblAusleihe(ByVal ausleiheEntity As AusleiheEntity)
        MyBase.AddObject("tblAusleihe", ausleiheEntity)
    End Sub

    ''' <summary>
    ''' Veraltete Methode zum Hinzufügen eines neuen Objekts zum EntitySet 'tblBenutzer'. Verwenden Sie stattdessen die Methode '.Add' der zugeordneten Eigenschaft 'ObjectSet(Of T) '.
    ''' </summary>
    Public Sub AddTotblBenutzer(ByVal benutzerEntity As BenutzerEntity)
        MyBase.AddObject("tblBenutzer", benutzerEntity)
    End Sub

    ''' <summary>
    ''' Veraltete Methode zum Hinzufügen eines neuen Objekts zum EntitySet 'tblGegenstand'. Verwenden Sie stattdessen die Methode '.Add' der zugeordneten Eigenschaft 'ObjectSet(Of T) '.
    ''' </summary>
    Public Sub AddTotblGegenstand(ByVal gegenstandEntity As GegenstandEntity)
        MyBase.AddObject("tblGegenstand", gegenstandEntity)
    End Sub

    ''' <summary>
    ''' Veraltete Methode zum Hinzufügen eines neuen Objekts zum EntitySet 'tblKategorie'. Verwenden Sie stattdessen die Methode '.Add' der zugeordneten Eigenschaft 'ObjectSet(Of T) '.
    ''' </summary>
    Public Sub AddTotblKategorie(ByVal kategorieEntity As KategorieEntity)
        MyBase.AddObject("tblKategorie", kategorieEntity)
    End Sub

    ''' <summary>
    ''' Veraltete Methode zum Hinzufügen eines neuen Objekts zum EntitySet 'tblnachbarschaft'. Verwenden Sie stattdessen die Methode '.Add' der zugeordneten Eigenschaft 'ObjectSet(Of T) '.
    ''' </summary>
    Public Sub AddTotblnachbarschaft(ByVal nachbarschaftEntity As NachbarschaftEntity)
        MyBase.AddObject("tblnachbarschaft", nachbarschaftEntity)
    End Sub

    #End Region

End Class

#End Region

#Region "Entitäten"

''' <summary>
''' Keine Dokumentation für Metadaten verfügbar.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="Datenbank1Model", Name:="AusleiheEntity")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class AusleiheEntity
    Inherits EntityObject
    #Region "Factory-Methode"

    ''' <summary>
    ''' Erstellt ein neues AusleiheEntity-Objekt.
    ''' </summary>
    ''' <param name="ausID">Anfangswert der Eigenschaft ausID.</param>
    ''' <param name="ausgegIDFk">Anfangswert der Eigenschaft ausgegIDFk.</param>
    ''' <param name="ausbenBenutzernameFk">Anfangswert der Eigenschaft ausbenBenutzernameFk.</param>
    Public Shared Function CreateAusleiheEntity(ausID As Global.System.Int32, ausgegIDFk As Global.System.Int32, ausbenBenutzernameFk As Global.System.String) As AusleiheEntity
        Dim ausleiheEntity as AusleiheEntity = New AusleiheEntity
        ausleiheEntity.ausID = ausID
        ausleiheEntity.ausgegIDFk = ausgegIDFk
        ausleiheEntity.ausbenBenutzernameFk = ausbenBenutzernameFk
        Return ausleiheEntity
    End Function

    #End Region

    #Region "Einfache Eigenschaften"

    ''' <summary>
    ''' Keine Dokumentation für Metadaten verfügbar.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property ausID() As Global.System.Int32
        Get
            Return _ausID
        End Get
        Set
            If (_ausID <> Value) Then
                OnausIDChanging(value)
                ReportPropertyChanging("ausID")
                _ausID = StructuralObject.SetValidValue(value, "ausID")
                ReportPropertyChanged("ausID")
                OnausIDChanged()
            End If
        End Set
    End Property

    Private _ausID As Global.System.Int32
    Private Partial Sub OnausIDChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnausIDChanged()
    End Sub

    ''' <summary>
    ''' Keine Dokumentation für Metadaten verfügbar.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property ausStart() As Nullable(Of Global.System.DateTime)
        Get
            Return _ausStart
        End Get
        Set
            OnausStartChanging(value)
            ReportPropertyChanging("ausStart")
            _ausStart = StructuralObject.SetValidValue(value, "ausStart")
            ReportPropertyChanged("ausStart")
            OnausStartChanged()
        End Set
    End Property

    Private _ausStart As Nullable(Of Global.System.DateTime)
    Private Partial Sub OnausStartChanging(value As Nullable(Of Global.System.DateTime))
    End Sub

    Private Partial Sub OnausStartChanged()
    End Sub

    ''' <summary>
    ''' Keine Dokumentation für Metadaten verfügbar.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property ausEnde() As Nullable(Of Global.System.DateTime)
        Get
            Return _ausEnde
        End Get
        Set
            OnausEndeChanging(value)
            ReportPropertyChanging("ausEnde")
            _ausEnde = StructuralObject.SetValidValue(value, "ausEnde")
            ReportPropertyChanged("ausEnde")
            OnausEndeChanged()
        End Set
    End Property

    Private _ausEnde As Nullable(Of Global.System.DateTime)
    Private Partial Sub OnausEndeChanging(value As Nullable(Of Global.System.DateTime))
    End Sub

    Private Partial Sub OnausEndeChanged()
    End Sub

    ''' <summary>
    ''' Keine Dokumentation für Metadaten verfügbar.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property ausgegIDFk() As Global.System.Int32
        Get
            Return _ausgegIDFk
        End Get
        Set
            OnausgegIDFkChanging(value)
            ReportPropertyChanging("ausgegIDFk")
            _ausgegIDFk = StructuralObject.SetValidValue(value, "ausgegIDFk")
            ReportPropertyChanged("ausgegIDFk")
            OnausgegIDFkChanged()
        End Set
    End Property

    Private _ausgegIDFk As Global.System.Int32
    Private Partial Sub OnausgegIDFkChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnausgegIDFkChanged()
    End Sub

    ''' <summary>
    ''' Keine Dokumentation für Metadaten verfügbar.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property ausbenBenutzernameFk() As Global.System.String
        Get
            Return _ausbenBenutzernameFk
        End Get
        Set
            OnausbenBenutzernameFkChanging(value)
            ReportPropertyChanging("ausbenBenutzernameFk")
            _ausbenBenutzernameFk = StructuralObject.SetValidValue(value, false, "ausbenBenutzernameFk")
            ReportPropertyChanged("ausbenBenutzernameFk")
            OnausbenBenutzernameFkChanged()
        End Set
    End Property

    Private _ausbenBenutzernameFk As Global.System.String
    Private Partial Sub OnausbenBenutzernameFkChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnausbenBenutzernameFkChanged()
    End Sub

    #End Region

    #Region "Navigationseigenschaften"

    ''' <summary>
    ''' Keine Dokumentation für Metadaten verfügbar.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("Datenbank1Model", "ausbenBenutzernameFk", "tblBenutzer")>
    Public Property tblBenutzer() As BenutzerEntity
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of BenutzerEntity)("Datenbank1Model.ausbenBenutzernameFk", "tblBenutzer").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of BenutzerEntity)("Datenbank1Model.ausbenBenutzernameFk", "tblBenutzer").Value = value
        End Set
    End Property
    ''' <summary>
    ''' Keine Dokumentation für Metadaten verfügbar.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property tblBenutzerReference() As EntityReference(Of BenutzerEntity)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of BenutzerEntity)("Datenbank1Model.ausbenBenutzernameFk", "tblBenutzer")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of BenutzerEntity)("Datenbank1Model.ausbenBenutzernameFk", "tblBenutzer", value)
            End If
        End Set
    End Property

    ''' <summary>
    ''' Keine Dokumentation für Metadaten verfügbar.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("Datenbank1Model", "ausgegIDFk", "tblGegenstand")>
    Public Property tblGegenstand() As GegenstandEntity
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of GegenstandEntity)("Datenbank1Model.ausgegIDFk", "tblGegenstand").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of GegenstandEntity)("Datenbank1Model.ausgegIDFk", "tblGegenstand").Value = value
        End Set
    End Property
    ''' <summary>
    ''' Keine Dokumentation für Metadaten verfügbar.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property tblGegenstandReference() As EntityReference(Of GegenstandEntity)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of GegenstandEntity)("Datenbank1Model.ausgegIDFk", "tblGegenstand")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of GegenstandEntity)("Datenbank1Model.ausgegIDFk", "tblGegenstand", value)
            End If
        End Set
    End Property

    #End Region

End Class

''' <summary>
''' Keine Dokumentation für Metadaten verfügbar.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="Datenbank1Model", Name:="BenutzerEntity")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class BenutzerEntity
    Inherits EntityObject
    #Region "Factory-Methode"

    ''' <summary>
    ''' Erstellt ein neues BenutzerEntity-Objekt.
    ''' </summary>
    ''' <param name="benBenutzername">Anfangswert der Eigenschaft benBenutzername.</param>
    ''' <param name="benPasswort">Anfangswert der Eigenschaft benPasswort.</param>
    ''' <param name="benVorname">Anfangswert der Eigenschaft benVorname.</param>
    ''' <param name="benName">Anfangswert der Eigenschaft benName.</param>
    ''' <param name="benGeburtsdatum">Anfangswert der Eigenschaft benGeburtsdatum.</param>
    ''' <param name="benScore">Anfangswert der Eigenschaft benScore.</param>
    ''' <param name="benIstKoordinator">Anfangswert der Eigenschaft benIstKoordinator.</param>
    ''' <param name="benIstEigentümer">Anfangswert der Eigenschaft benIstEigentümer.</param>
    ''' <param name="bennachIDFk">Anfangswert der Eigenschaft bennachIDFk.</param>
    Public Shared Function CreateBenutzerEntity(benBenutzername As Global.System.String, benPasswort As Global.System.String, benVorname As Global.System.String, benName As Global.System.String, benGeburtsdatum As Global.System.DateTime, benScore As Global.System.Int32, benIstKoordinator As Global.System.Boolean, benIstEigentümer As Global.System.Boolean, bennachIDFk As Global.System.Int32) As BenutzerEntity
        Dim benutzerEntity as BenutzerEntity = New BenutzerEntity
        benutzerEntity.benBenutzername = benBenutzername
        benutzerEntity.benPasswort = benPasswort
        benutzerEntity.benVorname = benVorname
        benutzerEntity.benName = benName
        benutzerEntity.benGeburtsdatum = benGeburtsdatum
        benutzerEntity.benScore = benScore
        benutzerEntity.benIstKoordinator = benIstKoordinator
        benutzerEntity.benIstEigentümer = benIstEigentümer
        benutzerEntity.bennachIDFk = bennachIDFk
        Return benutzerEntity
    End Function

    #End Region

    #Region "Einfache Eigenschaften"

    ''' <summary>
    ''' Keine Dokumentation für Metadaten verfügbar.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property benBenutzername() As Global.System.String
        Get
            Return _benBenutzername
        End Get
        Set
            If (_benBenutzername <> Value) Then
                OnbenBenutzernameChanging(value)
                ReportPropertyChanging("benBenutzername")
                _benBenutzername = StructuralObject.SetValidValue(value, false, "benBenutzername")
                ReportPropertyChanged("benBenutzername")
                OnbenBenutzernameChanged()
            End If
        End Set
    End Property

    Private _benBenutzername As Global.System.String
    Private Partial Sub OnbenBenutzernameChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnbenBenutzernameChanged()
    End Sub

    ''' <summary>
    ''' Keine Dokumentation für Metadaten verfügbar.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property benPasswort() As Global.System.String
        Get
            Return _benPasswort
        End Get
        Set
            OnbenPasswortChanging(value)
            ReportPropertyChanging("benPasswort")
            _benPasswort = StructuralObject.SetValidValue(value, false, "benPasswort")
            ReportPropertyChanged("benPasswort")
            OnbenPasswortChanged()
        End Set
    End Property

    Private _benPasswort As Global.System.String
    Private Partial Sub OnbenPasswortChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnbenPasswortChanged()
    End Sub

    ''' <summary>
    ''' Keine Dokumentation für Metadaten verfügbar.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property benVorname() As Global.System.String
        Get
            Return _benVorname
        End Get
        Set
            OnbenVornameChanging(value)
            ReportPropertyChanging("benVorname")
            _benVorname = StructuralObject.SetValidValue(value, false, "benVorname")
            ReportPropertyChanged("benVorname")
            OnbenVornameChanged()
        End Set
    End Property

    Private _benVorname As Global.System.String
    Private Partial Sub OnbenVornameChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnbenVornameChanged()
    End Sub

    ''' <summary>
    ''' Keine Dokumentation für Metadaten verfügbar.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property benName() As Global.System.String
        Get
            Return _benName
        End Get
        Set
            OnbenNameChanging(value)
            ReportPropertyChanging("benName")
            _benName = StructuralObject.SetValidValue(value, false, "benName")
            ReportPropertyChanged("benName")
            OnbenNameChanged()
        End Set
    End Property

    Private _benName As Global.System.String
    Private Partial Sub OnbenNameChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnbenNameChanged()
    End Sub

    ''' <summary>
    ''' Keine Dokumentation für Metadaten verfügbar.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property benEmail() As Global.System.String
        Get
            Return _benEmail
        End Get
        Set
            OnbenEmailChanging(value)
            ReportPropertyChanging("benEmail")
            _benEmail = StructuralObject.SetValidValue(value, true, "benEmail")
            ReportPropertyChanged("benEmail")
            OnbenEmailChanged()
        End Set
    End Property

    Private _benEmail As Global.System.String
    Private Partial Sub OnbenEmailChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnbenEmailChanged()
    End Sub

    ''' <summary>
    ''' Keine Dokumentation für Metadaten verfügbar.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property benTelefonnummer() As Global.System.String
        Get
            Return _benTelefonnummer
        End Get
        Set
            OnbenTelefonnummerChanging(value)
            ReportPropertyChanging("benTelefonnummer")
            _benTelefonnummer = StructuralObject.SetValidValue(value, true, "benTelefonnummer")
            ReportPropertyChanged("benTelefonnummer")
            OnbenTelefonnummerChanged()
        End Set
    End Property

    Private _benTelefonnummer As Global.System.String
    Private Partial Sub OnbenTelefonnummerChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnbenTelefonnummerChanged()
    End Sub

    ''' <summary>
    ''' Keine Dokumentation für Metadaten verfügbar.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property benGeburtsdatum() As Global.System.DateTime
        Get
            Return _benGeburtsdatum
        End Get
        Set
            OnbenGeburtsdatumChanging(value)
            ReportPropertyChanging("benGeburtsdatum")
            _benGeburtsdatum = StructuralObject.SetValidValue(value, "benGeburtsdatum")
            ReportPropertyChanged("benGeburtsdatum")
            OnbenGeburtsdatumChanged()
        End Set
    End Property

    Private _benGeburtsdatum As Global.System.DateTime
    Private Partial Sub OnbenGeburtsdatumChanging(value As Global.System.DateTime)
    End Sub

    Private Partial Sub OnbenGeburtsdatumChanged()
    End Sub

    ''' <summary>
    ''' Keine Dokumentation für Metadaten verfügbar.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property benScore() As Global.System.Int32
        Get
            Return _benScore
        End Get
        Set
            OnbenScoreChanging(value)
            ReportPropertyChanging("benScore")
            _benScore = StructuralObject.SetValidValue(value, "benScore")
            ReportPropertyChanged("benScore")
            OnbenScoreChanged()
        End Set
    End Property

    Private _benScore As Global.System.Int32
    Private Partial Sub OnbenScoreChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnbenScoreChanged()
    End Sub

    ''' <summary>
    ''' Keine Dokumentation für Metadaten verfügbar.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property benIstKoordinator() As Global.System.Boolean
        Get
            Return _benIstKoordinator
        End Get
        Set
            OnbenIstKoordinatorChanging(value)
            ReportPropertyChanging("benIstKoordinator")
            _benIstKoordinator = StructuralObject.SetValidValue(value, "benIstKoordinator")
            ReportPropertyChanged("benIstKoordinator")
            OnbenIstKoordinatorChanged()
        End Set
    End Property

    Private _benIstKoordinator As Global.System.Boolean
    Private Partial Sub OnbenIstKoordinatorChanging(value As Global.System.Boolean)
    End Sub

    Private Partial Sub OnbenIstKoordinatorChanged()
    End Sub

    ''' <summary>
    ''' Keine Dokumentation für Metadaten verfügbar.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property benIstEigentümer() As Global.System.Boolean
        Get
            Return _benIstEigentümer
        End Get
        Set
            OnbenIstEigentümerChanging(value)
            ReportPropertyChanging("benIstEigentümer")
            _benIstEigentümer = StructuralObject.SetValidValue(value, "benIstEigentümer")
            ReportPropertyChanged("benIstEigentümer")
            OnbenIstEigentümerChanged()
        End Set
    End Property

    Private _benIstEigentümer As Global.System.Boolean
    Private Partial Sub OnbenIstEigentümerChanging(value As Global.System.Boolean)
    End Sub

    Private Partial Sub OnbenIstEigentümerChanged()
    End Sub

    ''' <summary>
    ''' Keine Dokumentation für Metadaten verfügbar.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property bennachIDFk() As Global.System.Int32
        Get
            Return _bennachIDFk
        End Get
        Set
            OnbennachIDFkChanging(value)
            ReportPropertyChanging("bennachIDFk")
            _bennachIDFk = StructuralObject.SetValidValue(value, "bennachIDFk")
            ReportPropertyChanged("bennachIDFk")
            OnbennachIDFkChanged()
        End Set
    End Property

    Private _bennachIDFk As Global.System.Int32
    Private Partial Sub OnbennachIDFkChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnbennachIDFkChanged()
    End Sub

    #End Region

    #Region "Navigationseigenschaften"

    ''' <summary>
    ''' Keine Dokumentation für Metadaten verfügbar.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("Datenbank1Model", "ausbenBenutzernameFk", "tblAusleihe")>
     Public Property tblAusleihe() As EntityCollection(Of AusleiheEntity)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of AusleiheEntity)("Datenbank1Model.ausbenBenutzernameFk", "tblAusleihe")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of AusleiheEntity)("Datenbank1Model.ausbenBenutzernameFk", "tblAusleihe", value)
            End If
        End Set
    End Property

    ''' <summary>
    ''' Keine Dokumentation für Metadaten verfügbar.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("Datenbank1Model", "bennachIDFk", "tblnachbarschaft")>
    Public Property tblnachbarschaft() As NachbarschaftEntity
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of NachbarschaftEntity)("Datenbank1Model.bennachIDFk", "tblnachbarschaft").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of NachbarschaftEntity)("Datenbank1Model.bennachIDFk", "tblnachbarschaft").Value = value
        End Set
    End Property
    ''' <summary>
    ''' Keine Dokumentation für Metadaten verfügbar.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property tblnachbarschaftReference() As EntityReference(Of NachbarschaftEntity)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of NachbarschaftEntity)("Datenbank1Model.bennachIDFk", "tblnachbarschaft")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of NachbarschaftEntity)("Datenbank1Model.bennachIDFk", "tblnachbarschaft", value)
            End If
        End Set
    End Property

    ''' <summary>
    ''' Keine Dokumentation für Metadaten verfügbar.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("Datenbank1Model", "gegbenIDFk", "tblGegenstand")>
     Public Property tblGegenstand() As EntityCollection(Of GegenstandEntity)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of GegenstandEntity)("Datenbank1Model.gegbenIDFk", "tblGegenstand")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of GegenstandEntity)("Datenbank1Model.gegbenIDFk", "tblGegenstand", value)
            End If
        End Set
    End Property

    #End Region

End Class

''' <summary>
''' Keine Dokumentation für Metadaten verfügbar.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="Datenbank1Model", Name:="GegenstandEntity")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class GegenstandEntity
    Inherits EntityObject
    #Region "Factory-Methode"

    ''' <summary>
    ''' Erstellt ein neues GegenstandEntity-Objekt.
    ''' </summary>
    ''' <param name="gegID_">Anfangswert der Eigenschaft gegID_.</param>
    ''' <param name="gegBezeichnung">Anfangswert der Eigenschaft gegBezeichnung.</param>
    ''' <param name="gegIstGebucht">Anfangswert der Eigenschaft gegIstGebucht.</param>
    ''' <param name="gegnachIDFk">Anfangswert der Eigenschaft gegnachIDFk.</param>
    ''' <param name="gegbenBenutzernameFk">Anfangswert der Eigenschaft gegbenBenutzernameFk.</param>
    ''' <param name="gegkatKategorieFk">Anfangswert der Eigenschaft gegkatKategorieFk.</param>
    Public Shared Function CreateGegenstandEntity(gegID_ As Global.System.Int32, gegBezeichnung As Global.System.String, gegIstGebucht As Global.System.Boolean, gegnachIDFk As Global.System.Int32, gegbenBenutzernameFk As Global.System.String, gegkatKategorieFk As Global.System.Int32) As GegenstandEntity
        Dim gegenstandEntity as GegenstandEntity = New GegenstandEntity
        gegenstandEntity.gegID_ = gegID_
        gegenstandEntity.gegBezeichnung = gegBezeichnung
        gegenstandEntity.gegIstGebucht = gegIstGebucht
        gegenstandEntity.gegnachIDFk = gegnachIDFk
        gegenstandEntity.gegbenBenutzernameFk = gegbenBenutzernameFk
        gegenstandEntity.gegkatKategorieFk = gegkatKategorieFk
        Return gegenstandEntity
    End Function

    #End Region

    #Region "Einfache Eigenschaften"

    ''' <summary>
    ''' Keine Dokumentation für Metadaten verfügbar.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property gegID_() As Global.System.Int32
        Get
            Return _gegID_
        End Get
        Set
            If (_gegID_ <> Value) Then
                OngegID_Changing(value)
                ReportPropertyChanging("gegID_")
                _gegID_ = StructuralObject.SetValidValue(value, "gegID_")
                ReportPropertyChanged("gegID_")
                OngegID_Changed()
            End If
        End Set
    End Property

    Private _gegID_ As Global.System.Int32
    Private Partial Sub OngegID_Changing(value As Global.System.Int32)
    End Sub

    Private Partial Sub OngegID_Changed()
    End Sub

    ''' <summary>
    ''' Keine Dokumentation für Metadaten verfügbar.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property gegBezeichnung() As Global.System.String
        Get
            Return _gegBezeichnung
        End Get
        Set
            OngegBezeichnungChanging(value)
            ReportPropertyChanging("gegBezeichnung")
            _gegBezeichnung = StructuralObject.SetValidValue(value, false, "gegBezeichnung")
            ReportPropertyChanged("gegBezeichnung")
            OngegBezeichnungChanged()
        End Set
    End Property

    Private _gegBezeichnung As Global.System.String
    Private Partial Sub OngegBezeichnungChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OngegBezeichnungChanged()
    End Sub

    ''' <summary>
    ''' Keine Dokumentation für Metadaten verfügbar.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property gegIstGebucht() As Global.System.Boolean
        Get
            Return _gegIstGebucht
        End Get
        Set
            OngegIstGebuchtChanging(value)
            ReportPropertyChanging("gegIstGebucht")
            _gegIstGebucht = StructuralObject.SetValidValue(value, "gegIstGebucht")
            ReportPropertyChanged("gegIstGebucht")
            OngegIstGebuchtChanged()
        End Set
    End Property

    Private _gegIstGebucht As Global.System.Boolean
    Private Partial Sub OngegIstGebuchtChanging(value As Global.System.Boolean)
    End Sub

    Private Partial Sub OngegIstGebuchtChanged()
    End Sub

    ''' <summary>
    ''' Keine Dokumentation für Metadaten verfügbar.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property gegBild() As Global.System.Byte()
        Get
                Return StructuralObject.GetValidValue(_gegBild)
        End Get
        Set
            OngegBildChanging(value)
            ReportPropertyChanging("gegBild")
            _gegBild = StructuralObject.SetValidValue(value, true, "gegBild")
            ReportPropertyChanged("gegBild")
            OngegBildChanged()
        End Set
    End Property

    Private _gegBild As Global.System.Byte()
    Private Partial Sub OngegBildChanging(value As Global.System.Byte())
    End Sub

    Private Partial Sub OngegBildChanged()
    End Sub

    ''' <summary>
    ''' Keine Dokumentation für Metadaten verfügbar.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property gegnachIDFk() As Global.System.Int32
        Get
            Return _gegnachIDFk
        End Get
        Set
            OngegnachIDFkChanging(value)
            ReportPropertyChanging("gegnachIDFk")
            _gegnachIDFk = StructuralObject.SetValidValue(value, "gegnachIDFk")
            ReportPropertyChanged("gegnachIDFk")
            OngegnachIDFkChanged()
        End Set
    End Property

    Private _gegnachIDFk As Global.System.Int32
    Private Partial Sub OngegnachIDFkChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OngegnachIDFkChanged()
    End Sub

    ''' <summary>
    ''' Keine Dokumentation für Metadaten verfügbar.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property gegbenBenutzernameFk() As Global.System.String
        Get
            Return _gegbenBenutzernameFk
        End Get
        Set
            OngegbenBenutzernameFkChanging(value)
            ReportPropertyChanging("gegbenBenutzernameFk")
            _gegbenBenutzernameFk = StructuralObject.SetValidValue(value, false, "gegbenBenutzernameFk")
            ReportPropertyChanged("gegbenBenutzernameFk")
            OngegbenBenutzernameFkChanged()
        End Set
    End Property

    Private _gegbenBenutzernameFk As Global.System.String
    Private Partial Sub OngegbenBenutzernameFkChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OngegbenBenutzernameFkChanged()
    End Sub

    ''' <summary>
    ''' Keine Dokumentation für Metadaten verfügbar.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property gegkatKategorieFk() As Global.System.Int32
        Get
            Return _gegkatKategorieFk
        End Get
        Set
            OngegkatKategorieFkChanging(value)
            ReportPropertyChanging("gegkatKategorieFk")
            _gegkatKategorieFk = StructuralObject.SetValidValue(value, "gegkatKategorieFk")
            ReportPropertyChanged("gegkatKategorieFk")
            OngegkatKategorieFkChanged()
        End Set
    End Property

    Private _gegkatKategorieFk As Global.System.Int32
    Private Partial Sub OngegkatKategorieFkChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OngegkatKategorieFkChanged()
    End Sub

    #End Region

    #Region "Navigationseigenschaften"

    ''' <summary>
    ''' Keine Dokumentation für Metadaten verfügbar.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("Datenbank1Model", "ausgegIDFk", "tblAusleihe")>
     Public Property tblAusleihe() As EntityCollection(Of AusleiheEntity)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of AusleiheEntity)("Datenbank1Model.ausgegIDFk", "tblAusleihe")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of AusleiheEntity)("Datenbank1Model.ausgegIDFk", "tblAusleihe", value)
            End If
        End Set
    End Property

    ''' <summary>
    ''' Keine Dokumentation für Metadaten verfügbar.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("Datenbank1Model", "gegbenIDFk", "tblBenutzer")>
    Public Property tblBenutzer() As BenutzerEntity
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of BenutzerEntity)("Datenbank1Model.gegbenIDFk", "tblBenutzer").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of BenutzerEntity)("Datenbank1Model.gegbenIDFk", "tblBenutzer").Value = value
        End Set
    End Property
    ''' <summary>
    ''' Keine Dokumentation für Metadaten verfügbar.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property tblBenutzerReference() As EntityReference(Of BenutzerEntity)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of BenutzerEntity)("Datenbank1Model.gegbenIDFk", "tblBenutzer")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of BenutzerEntity)("Datenbank1Model.gegbenIDFk", "tblBenutzer", value)
            End If
        End Set
    End Property

    ''' <summary>
    ''' Keine Dokumentation für Metadaten verfügbar.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("Datenbank1Model", "gegkatKategorieFk", "tblKategorie")>
    Public Property tblKategorie() As KategorieEntity
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of KategorieEntity)("Datenbank1Model.gegkatKategorieFk", "tblKategorie").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of KategorieEntity)("Datenbank1Model.gegkatKategorieFk", "tblKategorie").Value = value
        End Set
    End Property
    ''' <summary>
    ''' Keine Dokumentation für Metadaten verfügbar.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property tblKategorieReference() As EntityReference(Of KategorieEntity)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of KategorieEntity)("Datenbank1Model.gegkatKategorieFk", "tblKategorie")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of KategorieEntity)("Datenbank1Model.gegkatKategorieFk", "tblKategorie", value)
            End If
        End Set
    End Property

    ''' <summary>
    ''' Keine Dokumentation für Metadaten verfügbar.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("Datenbank1Model", "gegnachIDFk", "tblnachbarschaft")>
    Public Property tblnachbarschaft() As NachbarschaftEntity
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of NachbarschaftEntity)("Datenbank1Model.gegnachIDFk", "tblnachbarschaft").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of NachbarschaftEntity)("Datenbank1Model.gegnachIDFk", "tblnachbarschaft").Value = value
        End Set
    End Property
    ''' <summary>
    ''' Keine Dokumentation für Metadaten verfügbar.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property tblnachbarschaftReference() As EntityReference(Of NachbarschaftEntity)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of NachbarschaftEntity)("Datenbank1Model.gegnachIDFk", "tblnachbarschaft")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of NachbarschaftEntity)("Datenbank1Model.gegnachIDFk", "tblnachbarschaft", value)
            End If
        End Set
    End Property

    #End Region

End Class

''' <summary>
''' Keine Dokumentation für Metadaten verfügbar.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="Datenbank1Model", Name:="KategorieEntity")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class KategorieEntity
    Inherits EntityObject
    #Region "Factory-Methode"

    ''' <summary>
    ''' Erstellt ein neues KategorieEntity-Objekt.
    ''' </summary>
    ''' <param name="katID">Anfangswert der Eigenschaft katID.</param>
    ''' <param name="katBezeichnung">Anfangswert der Eigenschaft katBezeichnung.</param>
    Public Shared Function CreateKategorieEntity(katID As Global.System.Int32, katBezeichnung As Global.System.String) As KategorieEntity
        Dim kategorieEntity as KategorieEntity = New KategorieEntity
        kategorieEntity.katID = katID
        kategorieEntity.katBezeichnung = katBezeichnung
        Return kategorieEntity
    End Function

    #End Region

    #Region "Einfache Eigenschaften"

    ''' <summary>
    ''' Keine Dokumentation für Metadaten verfügbar.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property katID() As Global.System.Int32
        Get
            Return _katID
        End Get
        Set
            If (_katID <> Value) Then
                OnkatIDChanging(value)
                ReportPropertyChanging("katID")
                _katID = StructuralObject.SetValidValue(value, "katID")
                ReportPropertyChanged("katID")
                OnkatIDChanged()
            End If
        End Set
    End Property

    Private _katID As Global.System.Int32
    Private Partial Sub OnkatIDChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnkatIDChanged()
    End Sub

    ''' <summary>
    ''' Keine Dokumentation für Metadaten verfügbar.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property katBezeichnung() As Global.System.String
        Get
            Return _katBezeichnung
        End Get
        Set
            OnkatBezeichnungChanging(value)
            ReportPropertyChanging("katBezeichnung")
            _katBezeichnung = StructuralObject.SetValidValue(value, false, "katBezeichnung")
            ReportPropertyChanged("katBezeichnung")
            OnkatBezeichnungChanged()
        End Set
    End Property

    Private _katBezeichnung As Global.System.String
    Private Partial Sub OnkatBezeichnungChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnkatBezeichnungChanged()
    End Sub

    #End Region

    #Region "Navigationseigenschaften"

    ''' <summary>
    ''' Keine Dokumentation für Metadaten verfügbar.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("Datenbank1Model", "gegkatKategorieFk", "tblGegenstand")>
     Public Property tblGegenstand() As EntityCollection(Of GegenstandEntity)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of GegenstandEntity)("Datenbank1Model.gegkatKategorieFk", "tblGegenstand")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of GegenstandEntity)("Datenbank1Model.gegkatKategorieFk", "tblGegenstand", value)
            End If
        End Set
    End Property

    #End Region

End Class

''' <summary>
''' Keine Dokumentation für Metadaten verfügbar.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="Datenbank1Model", Name:="NachbarschaftEntity")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class NachbarschaftEntity
    Inherits EntityObject
    #Region "Factory-Methode"

    ''' <summary>
    ''' Erstellt ein neues NachbarschaftEntity-Objekt.
    ''' </summary>
    ''' <param name="nachID">Anfangswert der Eigenschaft nachID.</param>
    ''' <param name="nachName">Anfangswert der Eigenschaft nachName.</param>
    ''' <param name="nachOrt">Anfangswert der Eigenschaft nachOrt.</param>
    Public Shared Function CreateNachbarschaftEntity(nachID As Global.System.Int32, nachName As Global.System.String, nachOrt As Global.System.String) As NachbarschaftEntity
        Dim nachbarschaftEntity as NachbarschaftEntity = New NachbarschaftEntity
        nachbarschaftEntity.nachID = nachID
        nachbarschaftEntity.nachName = nachName
        nachbarschaftEntity.nachOrt = nachOrt
        Return nachbarschaftEntity
    End Function

    #End Region

    #Region "Einfache Eigenschaften"

    ''' <summary>
    ''' Keine Dokumentation für Metadaten verfügbar.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property nachID() As Global.System.Int32
        Get
            Return _nachID
        End Get
        Set
            If (_nachID <> Value) Then
                OnnachIDChanging(value)
                ReportPropertyChanging("nachID")
                _nachID = StructuralObject.SetValidValue(value, "nachID")
                ReportPropertyChanged("nachID")
                OnnachIDChanged()
            End If
        End Set
    End Property

    Private _nachID As Global.System.Int32
    Private Partial Sub OnnachIDChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnnachIDChanged()
    End Sub

    ''' <summary>
    ''' Keine Dokumentation für Metadaten verfügbar.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property nachName() As Global.System.String
        Get
            Return _nachName
        End Get
        Set
            OnnachNameChanging(value)
            ReportPropertyChanging("nachName")
            _nachName = StructuralObject.SetValidValue(value, false, "nachName")
            ReportPropertyChanged("nachName")
            OnnachNameChanged()
        End Set
    End Property

    Private _nachName As Global.System.String
    Private Partial Sub OnnachNameChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnnachNameChanged()
    End Sub

    ''' <summary>
    ''' Keine Dokumentation für Metadaten verfügbar.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property nachOrt() As Global.System.String
        Get
            Return _nachOrt
        End Get
        Set
            OnnachOrtChanging(value)
            ReportPropertyChanging("nachOrt")
            _nachOrt = StructuralObject.SetValidValue(value, false, "nachOrt")
            ReportPropertyChanged("nachOrt")
            OnnachOrtChanged()
        End Set
    End Property

    Private _nachOrt As Global.System.String
    Private Partial Sub OnnachOrtChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnnachOrtChanged()
    End Sub

    #End Region

    #Region "Navigationseigenschaften"

    ''' <summary>
    ''' Keine Dokumentation für Metadaten verfügbar.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("Datenbank1Model", "bennachIDFk", "tblBenutzer")>
     Public Property tblBenutzer() As EntityCollection(Of BenutzerEntity)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of BenutzerEntity)("Datenbank1Model.bennachIDFk", "tblBenutzer")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of BenutzerEntity)("Datenbank1Model.bennachIDFk", "tblBenutzer", value)
            End If
        End Set
    End Property

    ''' <summary>
    ''' Keine Dokumentation für Metadaten verfügbar.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("Datenbank1Model", "gegnachIDFk", "tblGegenstand")>
     Public Property tblGegenstand() As EntityCollection(Of GegenstandEntity)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of GegenstandEntity)("Datenbank1Model.gegnachIDFk", "tblGegenstand")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of GegenstandEntity)("Datenbank1Model.gegnachIDFk", "tblGegenstand", value)
            End If
        End Set
    End Property

    #End Region

End Class

#End Region

