'------------------------------------------------------------------------------
' <auto-generated>
'     Der Code wurde von einer Vorlage generiert.
'
'     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
'     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class GegenstandEntity
    Public Property gegID_ As Integer
    Public Property gegBezeichnung As String
    Public Property gegIstGebucht As Boolean
    Public Property gegBild As Byte()
    Public Property gegnachIDFk As Integer
    Public Property gegbenBenutzernameFk As String
    Public Property gegkatKategorieFk As Integer

    Public Overridable Property tblKategorie As KategorieEntity

End Class
